[workspace]
members = ["mopro-ffi", "test-e2e", "cli", "mopro-wasm", "test-e2e/mopro-wasm-lib", "circom-prover"]
resolver = "2"
exclude = ["mopro-example-app"]

[workspace.dependencies]
plonk-fibonacci = { package = "plonk-fibonacci", git = "https://github.com/sifnoc/plonkish-fibonacci-sample.git" }
hyperplonk-fibonacci = { package = "hyperplonk-fibonacci", git = "https://github.com/sifnoc/plonkish-fibonacci-sample.git" }
gemini-fibonacci = { package = "gemini-fibonacci", git = "https://github.com/sifnoc/plonkish-fibonacci-sample.git" }
halo2-keccak-256 = { package = "halo2-keccak-256", git = "https://github.com/KimiWu123/halo2-keccak-stable.git", branch = "wasm32" }
mopro-halo2-rsa = { package = "mopro-halo2-rsa", git = "https://github.com/KimiWu123/halo2-rsa-mopro.git", branch = "wasm32" }

uniffi = { version = "=0.29.0" }

# patch for mopro_halo2_rsa
[patch."https://github.com/SoraSuegami/halo2-dynamic-sha256.git"]
halo2-dynamic-sha256 = { git = "https://github.com/SoraSuegami//halo2-dynamic-sha256.git", version = "0.1.0", rev = "46dc9c31ca0678bd4d047b54a2944ff2b3594f65"}
