[env]
MOPRO_FFI_LINK_TEST_WITNESS = ""
CIRCOM_PROVER_TEST_WITNESS = ""

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C",
    "link-arg=--max-memory=4294967296",
]

[unstable]
build-std = ["panic_abort", "std"]
